### PR TITLE
Alter disabling gpu accel

### PR DESCRIPTION
**Pull request by samkatakouzinosracing**
https://electronjs.org/docs/api/chrome-command-line-switches
https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md

https://electronjs.org/docs/api/app#appdisablehardwareacceleration
https://github.com/electron/electron/blob/master/docs/api/app.md#appdisablehardwareacceleration

As of 2018-08-03;
Electron command line argument --disable-gpu is not supported.
Electron method app.disableHardwareAcceleration() is supported.

The SimRacingApps Electron client seems more responsive and less resource hungry since removing the command line argument and adding the app method.

### CODE REVIEW

**Comment by jfgilliam** [comment]
Sam, you must not be using the embedded version of electron, because the version that is embedded uses the command line option.

**Comment by samkatakouzinosracing** [comment]
I have been replacing the electron-app with latest versions and seem to be enjoying a less stuttery iRacing experience.
I wasn't aware from which version of electron had stopped --disable-gpu as a valid argument.

**Comment by jfgilliam** [comment]
That's good to know. I've been playing around with affinity settings in Windows to help with the stuttering.

I see the latest version of Electron is v2.0.6. I will do some testing on that one and update to it as well. There's also a One Drive bug they put in v1.7 that I need to test was put in v2.0 as well.

All in all, it does look like v1.7 supports the API call also.

**Comment by jfgilliam** [comment]
Sam, I incorporated your changes into the 2018.08.20 release. I couldn't pull in your changes directly from this pull request because I wasn't sure what all the commits where doing. I also wanted to changed how the option will be used to turn it on and off. 

Thanks for your valuable input.

**Pull request closed without merging**
